config/routes.rb
Rails.application.routes.draw do
  namespace :super do
    get 'dashboard' => 'dashboard#index'
  end

  resources :sales do
    resources :videos do
    end
  end

  namespace :api do
    namespace :v1 do
      resources :sales
      post 'sales/:action' => 'sales#:action'
    end
  end

  devise_for :admins
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
                                        sessions:           'overrides/sessions'
                                    }

   root 'sales#index'

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :my_resources, :concerns => :paginatable

  resources :users
  resources :companies

  get 'dashboard/:action' => 'dashboard#:action'

end

app/models/super.rb
module Super
  def self.table_name_prefix
    'super_'
  end
end

app/models/super/dashboard.rb
class Super::Dashboard < ActiveRecord::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @admins = Admin.all
    @roles = Role.all
    @companies = Company.all
  end

  def dashboard_params
    params.require(:dashboard).permit(:email)
  end
end

app/controllers/super/dashboard_controller.rb
class Super::DashboardController < ApplicationController
  before_action :set_super_dashboard, only: [:show, :edit, :update, :destroy]
  # load_and_authorize_resource
  respond_to :html

  def index
    @companies = Company.all
    # respond_with(@companies)
    @admins = Admin.all

    @sales = Sale.all

    @users = User.all

  end

  def show

    @company = Company.find(params[:id])
    respond_with(@company)
  end

  def new
    @company = Company.new
    respond_with(@company)
  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    @company.save
    respond_with(@company)
  end

  def update
    @company.update(company_params)
    respond_with(@company)
  end

  def destroy
    @company.destroy
    respond_with(@company)
  end

  private
    def set_company
      @company = Company.find(params[:id])
    end

  def company_params
    params.require(:companies).permit(:name, :id)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/super/dashboards_helper.rb
module Super::DashboardsHelper
end

app/views/super/dashboards/_form.html.erb
<%= simple_form_for(@super_dashboard) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/super/dashboards/edit.html.erb
<h1>Editing super_dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @super_dashboard %> |
<%= link_to 'Back', super_dashboards_path %>

app/views/super/dashboards/index.html.erb
<h1>Listing super_dashboards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @super_dashboards.each do |super_dashboard| %>
      <tr>
        <td><%= link_to 'Show', super_dashboard %></td>
        <td><%= link_to 'Edit', edit_super_dashboard_path(super_dashboard) %></td>
        <td><%= link_to 'Destroy', super_dashboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dashboard', new_super_dashboard_path %>

app/views/super/dashboards/new.html.erb
<h1>New super_dashboard</h1>

<%= render 'form' %>

<%= link_to 'Back', super_dashboards_path %>

app/views/super/dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<% if current_admin %>

    signed in as <%= current_admin.email %>
<% end %>

companies:
<hr>
<% @companies.each do |company| %>
<%= link_to company.name, company %>
<br>
    <%end%>


<%= link_to 'Edit', edit_super_dashboard_path(@super_dashboard) %> |
<%= link_to 'Back', super_dashboards_path %>