config/routes.rb
Rails.application.routes.draw do
  namespace :super do
    get 'dashboard' => 'dashboard#index'
  end

  resources :sales do
    resources :videos do
    end
  end

  namespace :api do
    namespace :v1 do
      resources :sales
      post 'sales/:action' => 'sales#:action'
    end
  end

  devise_for :admins
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
                                        sessions:           'overrides/sessions'
                                    }

   root 'sales#index'

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :my_resources, :concerns => :paginatable

  resources :users
  resources :companies

  get 'dashboard/:action' => 'dashboard#:action'

end

app/models/company.rb
class Company < ActiveRecord::Base
  resourcify

  has_many :users
  has_many :admins
  has_many :sales, through: :users

  mount_uploader :company_image, CompanyImageUploader
  mount_uploader :logo, LogoUploader
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :html

  def new
    @company = Company.new
    respond_with(@company)

  end

  def index
    @companies = Company.all
    # @company = Company.find(params[:id])
    @admins = Admin.all
    @sales = Sale.all
    @users = User.all

    cities = []
    sales = Sale.all
    sales.each do |sale|
      if sale.description
        city = JSON.parse(sale.description.gsub('=>', ':'))["city"]
        cities << city
      end
    end
    @city_count = Hash.new 0
    cities.each do |city|
      @city_count[city] += 1
    end

    # countries = []
    # sales = Sale.all
    # sales.each do |sale|
    #   if sale.description
    #     country = JSON.parse(sale.description.gsub('=>', ':'))["city"]
    #     countries << country
    #   end
    # end
    # @country_count = Hash.new 0
    # countries.each do |country|
    #   @country_count[country] += 1
    # end

  end

  def create
    @company = Company.new(company_params)
    if @company.save
    @company.admins << Admin.create(email:params[:company][:admins][:email],password:params[:company][:admins][:password],password_confirmation:params[:company][:admins][:password_confirmation],company_id:@company.id)
    end
    respond_with(@company)
  end

  def show
      @company = Company.find(params[:id])
      if @user
        @user = User.find(params[:id])
      end
      @all_sales = @company.sales.all
      @q = @all_sales.search(params[:q])
      @sales = @q.result(distinct: true).order("created_at DESC").page(params[:page])
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company.update(company_params)
    if @company.save
      @company.admins << Admin.create(email:params[:company][:admins][:email],password:params[:company][:admins][:password],password_confirmation:params[:company][:admins][:password_confirmation],company_id:@company.id)
    end
    respond_with(@company)

  end

  private
  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name, :id, :email, :website,:stripe_publishable_key, :stripe_secret_key, :password, :password_confirmation, :company_image, :logo)
  end
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs form-group">
      <%= f.text_field :name, :placeholder => "Name", class: 'form-control' %> <br/>
      <%= f.text_field :website, :placeholder => "Website", class: 'form-control' %>
      <br/>
      <%= f.text_field :stripe_test_publishable_key, :placeholder => "Test - Stripe Publishable Key", class: 'form-control' %><br/>
      <%= f.text_field :stripe_test_secret_key, :placeholder => "Test - Stripe Secret Key", class: 'form-control' %> <br/>
      <%= f.text_field :stripe_publishable_key, :placeholder => "Stripe Publishable Key", class: 'form-control' %><br/>
      <%= f.text_field :stripe_secret_key, :placeholder => "Stripe Secret Key", class: 'form-control' %><br/>
      <%= f.label :logo %>
      <%= f.file_field :logo, :placeholder => "Company logo", class: 'form-control' %><br/>
      <%= f.label :company_image %>
      <%= f.file_field :company_image, :placeholder => "Company image", class: 'form-control' %><br/>
      <%= f.label 'Setup New Company Admin'%>
      <%= f.fields_for :admins do |ff|%>
      <%= ff.email_field :email, autofocus: true, :placeholder => "Email", class: 'form-control' %><br/>
          <%= ff.password_field :password, autofocus: true, :placeholder => "Password", class: 'form-control' %><br/>
          <%= ff.password_field :password_confirmation, autofocus: true, :placeholder => "Password Confirmation", class: 'form-control' %>
          <% end %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
      <br/> <br/>
    </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Edit Company Details</h1>

<br/>
<br/>

<% if @company.company_image.url%><%= link_to image_tag(@company.company_image.url) %> <% end %>

<% if @company.logo.url%><%= link_to image_tag(@company.logo.url) %> <% end %>

<% if @company.logo.url%><%#= link_to image_tag(@company.logo.thumb.url), @company.logo.detail.url %> test<% end %>



<br/>
<br/>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', company_path %>

app/views/companies/index.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>


<%#= pie_chart Sale.group(:user).count %>
<br/>
<div class="linechart" style="text-align:center;"><h4>Sales made this week</h4><%= line_chart Sale.group_by_day(:created_at, Time.zone.name, (7.days.ago..Time.now)).count, {library: {hAxis: {title: ""}, vAxis: {title: "Number of Sales"}}}%></div>
<div class="piechart"><h4>Sales by Company</h4><%= pie_chart Company.joins(:sales).group(:"companies.name").count %></div>

<%= geo_chart @city_count, library:{region: 'GB', displayMode: 'markers', resolution: 'provinces'} %>

<%#= geo_chart @country_count, library:{region: 'world', displayMode: 'regions', resolution: 'regions'} %>
<%#= geo_chart @city_count.group(:country).count %>

<%#= geo_chart Sale.group(:country).count %>

<br/>
<br/>


<% @companies.each do |company| %>
    <div class="row row-center" style="text-align:center; display:inline-block;">
      <div class="col-xs-12 custom-col">
        <div class="col-xs-3 logo-col">
        <% if company.logo%>
            <h3 style="color:#666;"><%= company.name[0].capitalize %></h3>
        <% else %>
            <%= link_to image_tag(company.logo.url, :height => 100, :width => 100) %>
        <% end %>
          </div>
        <div class="col-xs-9 listing-companies">
          <h3>
            <%= link_to company.try(:name).capitalize, company_path(company), class:"listing-companies-text" %>
          </h3>
        </div>

      </div>
    </div>
<% end %>

<br/>
<hr>
<br/>
<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<div class="main" ng-controller="CompanySalesController">

<%#= link_to image_tag(@company.company_image.url) %>

  <h1><%= @company.try(:name).capitalize %></h1>
<h5>Admins: <% @company.admins.each do |admin| %>
      <%= admin.email %><br>
      <% end %></h5>

  Number of sales <%= @company.sales.length%> <br/>
  Number of admins <%= @company.admins.length%><br/>
  Number of employees <%= @company.users.length%>

  <br/>

  <%= search_form_for @q, url: company_path do |f| %>
      <p>
        <%= f.text_field :user_email_cont, class: "form-control", placeholder: "Sales person / Company name"  %>
      </p>
      <p>
        <%= f.text_field :description_cont, class: "form-control", placeholder: "Customer / Location" %>
      </p>
      <p>
        <%= f.submit class:"btn" %>
      </p>
  <% end %>

  <br/><br/>

  <table class="table table-hover table-bordered">
    <thead>
    <tr class="info">
      <th class="col-md-2" style="padding-top:20px; padding-bottom:15px"><%= sort_link @q, :created_at %></th>
      <th class="col-md-2" style="padding-top:20px; padding-bottom:15px"><%= sort_link @q, :user, 'Sales person' %></th>
      <!--<th class="col-md-1">Price</th>-->
      <th class="col-md-2" style="padding-top:20px; padding-bottom:15px"><%= sort_link @q, :description, 'Customer' %></th>
      <th class="col-md-1" style="padding-top:20px; padding-bottom:15px"><%= sort_link @q, :location %></th>
      <th class="col-md-1" style="padding-top:20px; padding-bottom:15px"><%= sort_link @q, :paid %></th>
      <th class="col-md-1" style="padding-top:20px; padding-bottom:15px"><%= sort_link @q, :id, 'Sale id' %></th>
      <th class="col-md-2" style="padding-top:20px; padding-bottom:15px">Signature</th>
      <th class="col-md-1" style="padding-top:20px; padding-bottom:15px"></th>
    </tr>
    </thead>
    <tbody>
    <% @sales.each do |sale| %>
        <tr>
          <td><%= sale.created_at.strftime("%d %B") %>, <%= sale.created_at.strftime("%H:%M") %></td>
          <td><% if sale.user %> <%= sale.user.email %><% end %></td>

          <!--<td><%# if sale.description %>₤ <%#= JSON.parse(sale.description.gsub('=>', ':'))["price"] %><%# end %></td>-->
          <td><% if sale.description %><%= JSON.parse(sale.description.gsub('=>', ':'))["name"] %><% end %></td>
          <td><% if sale.description %><%= JSON.parse(sale.description.gsub('=>', ':'))["city"].capitalize %><% end %></td>

          <td><% if sale.paid %> £<%= JSON.parse(sale.description.gsub('=>', ':'))["price"]%><% else %> No <% end %></td>
          <td><%= sale.id %> </td>
          <td><%= image_tag sale.signature, size: "100x40"%></td>
          <td><%= link_to 'Show', sale, class: "btn btn-primary special-button"%></td>


        </tr>
    <% end %>
    </tbody>

  </table>
  <%= paginate @sales %>
  <br/>

<div class="linechart" style="text-align:center;"><h4>Sales this week</h4>
  <%= line_chart @company.sales.group_by_day('sales.created_at', Time.zone.name, (7.days.ago..Time.now)).count, {library: {hAxis: {title: ""}, vAxis: {title: "Number of Sales"}}} %></div>
  <div class="piechart" style="text-align:center;"><h4>Sales by Employee</h4> <%= pie_chart @company.sales.group(:'users.email').count %></div>

  <br/>
  <div class="ukmapcontainer">
    <input id="pac-input" class="controls" type="text" placeholder="Search Box">
    <div class="numberofsales"><span class="salecount"></span></div>
    <div id="ukmap_canvas" class="ukmap">

    </div>

    <br/>
    <br/>
    <br/>
    <br/>

<% if current_admin.has_role? :superadmin %>
    <%= link_to 'Edit Company', edit_company_path(@company) %>
<% end %>
<br/>

  </div>
<%if !current_admin.has_role? :superadmin %>
    <%= link_to 'New Employee', new_user_path %>
      <% end %>
</div>