config/routes.rb
Rails.application.routes.draw do
  namespace :super do
    get 'dashboard' => 'dashboard#index'
  end

  resources :sales do
    resources :videos do
    end
  end

  namespace :api do
    namespace :v1 do
      resources :sales
      post 'sales/:action' => 'sales#:action'
    end
  end

  devise_for :admins
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
                                        sessions:           'overrides/sessions'
                                    }

   root 'sales#index'

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :my_resources, :concerns => :paginatable

  resources :users
  resources :companies

  get 'dashboard/:action' => 'dashboard#:action'

end

app/models/super.rb
module Super
  def self.table_name_prefix
    'super_'
  end
end

app/models/super/dashboard.rb
class Super::Dashboard < ActiveRecord::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @admins = Admin.all
    @roles = Role.all
    @companies = Company.all
  end

  def dashboard_params
    params.require(:dashboard).permit(:email)
  end
end

app/controllers/super/dashboard_controller.rb
class Super::DashboardController < ApplicationController
  before_action :set_super_dashboard, only: [:show, :edit, :update, :destroy]
  # load_and_authorize_resource
  respond_to :html

  def index
    @companies = Company.all
    # respond_with(@companies)
    @admins = Admin.all

    @sales = Sale.all

    @users = User.all

  end

  def show

    @company = Company.find(params[:id])
    respond_with(@company)
  end

  def new
    @company = Company.new
    respond_with(@company)
  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    @company.save
    respond_with(@company)
  end

  def update
    @company.update(company_params)
    respond_with(@company)
  end

  def destroy
    @company.destroy
    respond_with(@company)
  end

  private
    def set_company
      @company = Company.find(params[:id])
    end

  def company_params
    params.require(:companies).permit(:name, :id)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/super/dashboards_helper.rb
module Super::DashboardsHelper
end

app/views/super/dashboard/_super_sidebar.html.erb
<ul class="nav nav-sidebar">
  welcome back <%= current_admin.email%><br>
  <%= current_admin.company.name%><br>
  <hr>
  cells gem here? - to show companies <br>
  <%= link_to 'view all companies', companies_path %><br>
  <%= link_to 'view all sales', sales_path %><br>
  <hr>
  <%= link_to 'New Company', new_company_path %>





</ul>

app/views/super/dashboard/index.html.erb
<%if current_admin %>

hi dere <%= current_admin.email%>

    <h3>companies: <% @companies.each do |company| %>
          <%= link_to company.name, company %>
      <% end %></h3>

<% else %>

not logged in

<%end %>